pipeline {
    agent any

    environment {
        // Define environment variables for Maven, SonarQube, and Artifactory
        // MAVEN_HOME = tool name: 'Maven 3.8.1', type: 'Maven'
        SONARQUBE_SERVER = 'SonarQube-Server'  // Replace with your SonarQube server ID
        ARTIFACTORY_SERVER = 'Artifactory'  // Replace with your Artifactory server ID
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout code from the repository
                git url: 'https://github.com/faisalkamilansari/jenkins-tomcat-deployment.git', branch: 'main'
            }
        }

        stage('Build') {
            steps {
                // Compile and package the application using Maven
                bat "cd calc && mvn clean install"
            }
        }
        stage('SonarQube Analysis'){
            steps
                {
                    withSonarQubeEnv(SONARQUBE_SERVER) {
                    bat "cd calc && mvn clean verify sonar:sonar -Dsonar.projectKey=Jenkins-tomcat-deployment"
                    }
                }
        }
        // stage('Code Analysis') {
        //     steps {
        //         // Run SonarQube analysis
        //         withSonarQubeEnv(SONARQUBE_SERVER) {
        //             bat "cd calc && mvn sonar:sonar"
        //         }
        //     }
        // }

        // stage('Upload to Artifactory') {
        //     steps {
        //         // Upload the packaged application to Artifactory
        //         script {
        //             def server = Artifactory.server(ARTIFACTORY_SERVER)
        //             def uploadSpec = """{
        //                 "files": [{
        //                     "pattern": "target/*.war",
        //                     "target": "libs-release-local/${env.JOB_NAME}/${env.BUILD_NUMBER}/"
        //                 }]
        //             }"""
        //             server.upload(uploadSpec)
        //         }
        //     }
        // }

        stage('Deploy to Tomcat') {
            steps {
                // Deploy to the appropriate Tomcat environment based on the input parameter
                    script {
                        def tomcatDir = 'C:\"Program Files (x86)"\"Apache Software Foundation"\"Tomcat 9.0"\"webapps"'
                        def warFile = "target\\myapp-${env.BUILD_NUMBER}.war"
                        def oldWarFile = "${tomcatDir}\\myapp.war"

                        bat """
                            if exist ${oldWarFile} del ${oldWarFile}
                            copy ${warFile} ${oldWarFile}
                        """
                        }
            }
        }
    }

    post {
        always {
            // Clean up workspace after the build
            cleanWs()
        }
        success {
            // Notify on successful build and deployment
            echo 'Deployment completed successfully!'
        }
        failure {
            // Notify on failure
            echo 'Deployment failed!'
        }
    }
}
